### ISSUE TITLE
login button font not centered. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#631] opened 2020-11-04 21:43 UTC
Using a Mac, the font on the login button that says "login" isn't centered. 

<img width="419" alt="image" src="https://user-images.githubusercontent.com/10395907/98128992-39d67280-1e7e-11eb-9d1d-605400b24614.png">

**Comment by garm01** [comment] 2020-11-15 13:10
the same here:
![Wallet-button](https://user-images.githubusercontent.com/46584115/99185745-2bc10580-274c-11eb-9851-b62dbd5f777f.png)

**Comment by myxmaster** [comment] 2021-01-17 14:47
Probably duplicate of #813. Both issues have pull requests (#863 and #890) with different solutions...

**Comment by myxmaster** [comment] 2021-01-17 14:53
@garm01 I created a seperate issue for that (#919) since the cause is not the same.

**Comment by cryptoBeliever** [comment] 2021-01-27 07:01
@NikolaiB could you check on Mac (login and download buttons)?

**Comment by NikolaiB** [comment] 2021-01-27 07:03
@cryptoBeliever yes, it's centered (Version: 0.13.8)

**Comment by cryptoBeliever** [comment] 2021-01-27 07:41
Ok. Closing.

**Closed by cryptoBeliever** 2021-01-27 07:41 UTC
Labels: P3 Issue, aesthetic bug, story-2
