### ISSUE TITLE
Encrypted messages are decrypted but are not displayed

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#623] opened 2020-11-03 03:23 UTC
Encrypted messages are decrypted but are not displayed on Details about a transaction.

**Comment by cryptoBeliever** [comment] 2020-11-03 05:26
I checked on deb version and it worked well. Could you please tell which one build from https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.2 are you using?

**Comment by trestoJP** [comment] 2020-11-03 06:18
Of course.
After checking, it seems that only in the case of a multi-sig transaction, it is not decrypted. Recipients did not see the message when decrypting it after receiving it.

It appears that a co-signer who is not a recipient can also decrypt in this way, but it does not appear. I don't think it is necessary to be displayed because this co-signer is not a receiver, but do we need to use the decryption button?
![2020-11-03 15-03-07-214](https://user-images.githubusercontent.com/59822825/97954704-9aff3700-1de7-11eb-9296-d010e621615e.png)

**Comment by cryptoBeliever** [comment] 2020-11-03 07:10
@trestoJP thanks. This was the missing part. I checked for regular account and you for multisig. Now I'm able to reproduce. Thanks :+1: 

Steps to reproduce:
1. Create multisig transfer transaction with encrypted message.
2. Sign it to be confirmed.

Decrypt button is visible in transaction details:
- for cosigners who didn't initialize transaction (should be?) but it doesn't work (blank value presented)
- recipient but it doesn't work (blank value presented)
- sender cosigner and it works (I can decrypt and value is presented).

Same thing before confirmation - only cosigner sender is able to decrypt message from unconfirmed transaction.

**Comment by cryptoBeliever** [comment] 2020-11-11 23:20
@trestoJP encrypted messages for multi-sig are blocked now. It's because cosigner don't know (in most cases) private key of multi-sig account.

**Comment by cryptoBeliever** [comment] 2020-11-19 06:36
Closing (look comment above). Encrypted messages not available for multisig.

**Closed by cryptoBeliever** 2020-11-19 06:36 UTC
