### ISSUE TITLE
Make a "ding" sound when a tx confirms

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1365] opened 2021-03-24 17:08 UTC
One thing that has connected NEM community members throughout the years is that annoying "ding" sound when txs confirm, but it really grows on people and they really love it after a while. It really just works. It is also a great notifier that the tx has confirmed and now you can move on to the next step, whatever that is, in your operation. It makes things more efficient. The same file can easily be found in the NanoWallet Github.

**Comment by Peersyst** [comment] 2021-03-25 08:31
Thanks @jabo38 . Closing it as it's Duplicate of #1362

**Closed by Peersyst** 2021-03-25 08:31 UTC
