### ISSUE TITLE
URI link "Copy" button is mocking me!

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#848] opened 2020-12-23 10:34 UTC
This is a funny one! Go to the Invoice page, there should be an URI link at the bottom:
![image](https://user-images.githubusercontent.com/10949043/102987232-543ddb80-4512-11eb-989a-27dd5d8c933a.png)
If you hover your mouse over the "copy" button, a popup appears, but it is partially hidden:
![image](https://user-images.githubusercontent.com/10949043/102987304-69b30580-4512-11eb-8cd5-afceffef1eff.png)
I want to see this popup, so I scroll down with the mouse wheel and the button appears:
![image](https://user-images.githubusercontent.com/10949043/102987365-7a637b80-4512-11eb-8d19-5e3a615d0c4b.png)
**Good luck trying to click the button now!**
When you move the mouse up the popup disappears and the button falls down. When you move your mouse down the popup appears and the button moves up again.
You have invented Artificial Intelligence!

**Comment by cryptoBeliever** [comment] 2020-12-24 19:24
Looks like duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/671
Should be fixed in http://desktop-build.symboldev.com/

**Closed by cryptoBeliever** 2020-12-24 19:24 UTC
