### ISSUE TITLE
Transfer tab is inactive after toggling to Multisig account and back to non-Multisig

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#871] opened 2021-01-05 13:29 UTC
**Steps to reproduce:**

1. Go to the Transfer tab under non-Multisig account
2. Switch to the Multisig account via upper menu
3. Switch back to any non-Multisig account within the profile
4. Try to paste any data into fields or use the Send button

**Actual result:** The fields on the Transfer tab do not accept data
**Expected result:** The fields and the Send button are responsive after toggling back to non-Multisig account

[Video](https://share.getcloudapp.com/d5uP2GBg)

**Comment by cryptoBeliever** [comment] 2021-02-06 18:47
Confirmed. Would be nice to fix that because it's annoying :)

**Comment by Eugenity** [comment] 2021-02-08 09:28
Please be informed that the same behavior expectedly is for text fields on the **Mosaics**, **Namespaces** and respectively on the **Aggregate** pages (for simple transaction, mosaics and namespace creation).

**Comment by bassemmagdy** [comment] 2021-02-12 15:52
fixed on latest integration

**Comment by bassemmagdy** [comment] 2021-02-12 15:53
fixed on latest integration

**Closed by bassemmagdy** 2021-02-12 15:53 UTC
Labels: P3 Issue
