### ISSUE TITLE
Namespace - why is the amount not displayed in dashoard

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#803] opened 2020-12-10 11:50 UTC
After creating the namespace, why is the amount not displayed in the dashboard instead showing N/A
![image](https://user-images.githubusercontent.com/49143210/101768662-df2ed700-3b0b-11eb-89e0-c4abe4ee9f63.png)
![image](https://user-images.githubusercontent.com/49143210/101768721-f2da3d80-3b0b-11eb-8d7f-bdfecad80a34.png)

**Comment by cryptoBeliever** [comment] 2020-12-10 21:42
@surekabpm in amount column is presented amount transferred for Transfer Transaction. Namespace creation is not Transfer Transaction.
I'm closing as not a bug

**Closed by cryptoBeliever** 2020-12-10 21:42 UTC
Labels: P3 Issue
