### ISSUE TITLE
Account restriction - outgoing operation restriction 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#786] opened 2020-12-09 06:12 UTC
I had initiated the operation restriction (outgoing) under address restriction , transaction is confirmed , then i tried to transfer aount XEM to another account, my understanding is that account restriction for outgoing for this address need to be restricted..in that case here the transfer transaction is working . is my understanding correct ? kindly review 
![image](https://user-images.githubusercontent.com/49143210/101591855-4cab0c80-3a13-11eb-81c6-e1d35fe937b8.png)
![image](https://user-images.githubusercontent.com/49143210/101592015-93006b80-3a13-11eb-9556-08f4bf2aff19.png)

**Comment by cryptoBeliever** [comment] 2020-12-10 22:37
@surekabpm you blocked here Outgoing transactions with type **Account address restrictions**.
It's not about all outgoing transactions but transaction with restrictions for **Account address**

Because of the above, I'm closing as not a bug.

**Closed by cryptoBeliever** 2020-12-10 22:37 UTC
