### ISSUE TITLE
Scaling issues on import passphrase page

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#533] opened 2020-10-02 20:22 UTC
There is an odd "copy" button visible. 

And "return to password settings" is too much wordage for a button. 

![image](https://user-images.githubusercontent.com/10395907/94966588-24f37180-04c3-11eb-8fa8-feac2ee72159.png)

**Comment by cryptoBeliever** [comment] 2020-10-03 15:04
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/522

**Comment by cryptoBeliever** [comment] 2020-11-19 09:48
Closing.

**Closed by cryptoBeliever** 2020-11-19 09:48 UTC
