### ISSUE TITLE
Sending by alias doesn't work

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#939] opened 2021-01-19 20:56 UTC
created an alias "jabo38.account" and linked it to an account. I can't send to it. 

created another alias "faucet" and linked it to an account. I can't send it. 

I always get an error. 

Using wallet version 0.13.8 on Mac

**Comment by cryptoBeliever** [comment] 2021-01-19 22:20
@jabo38 I believe this is duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/785

**Closed by cryptoBeliever** 2021-01-19 22:20 UTC

**Comment by jabo38** [comment] 2021-01-19 22:34
yes it is.
