### ISSUE TITLE
[Bug][Delegate Harvesting] While choosing multisig account to delegate harvesting getting TypeError: Cannot read property 'selectedHarvestingNode' of undefined

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#731] opened 2020-11-24 05:45 UTC
WTR:
1. Create multisig account from 2 separate desktop wallets (not child account)
2. Go to Harvesting page
3. Choose multisig account from **From** dropdown list

Result: When the account was chosen, getting error in console `TypeError: Cannot read property 'selectedHarvestingNode' of undefined`

![image](https://user-images.githubusercontent.com/11311924/100233326-c9d67c00-2f53-11eb-99a7-3b48f6ab75d2.png)

**Comment by yilmazbahadir** [comment] 2020-11-24 10:59
Can you please try the same steps with a fresh multi-sig account(or same account with stop and restart)? Because I think, in the first screenshot you shouldn't be seeing the "INACTIVE" status and "Activate" button at the same time. For the past deadline error, I suspect, it's been at least 24 hours since you first initiated the process because the deadline for multi-sig transactions is 24 hours.

**Comment by NikolaiB** [comment] 2020-11-24 12:07
@yilmazbahadir I am getting a new error now. Please find the updated description above.

**Comment by yilmazbahadir** [comment] 2020-11-24 12:55
Could you list the steps to reproduce?

**Comment by cryptoBeliever** [comment] 2020-12-02 18:34
@NikolaiB should be fixed. Please verify.

**Closed** 2020-12-03 06:53 UTC
Labels: P1 Issue, bug, story-5
