### ISSUE TITLE
warning before sending an aggregate to an exchange

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1451] opened 2021-04-20 14:55 UTC
it is known right now that all exchanges that have listed XYM do not process Multisig and/or aggregates. meaning anybody who is depositing from a Multisig account to an exchange won't see their funds arrive. 

I'm sure lots of people are making this mistake. 

We might want to consider a grey list of accounts that are known exchange deposit accounts and when a person pastes in that address into the send blank in the wallet, the wallet filters to see if it is one of those deposit addresses and if so shows a flag/warning that says in red something like the following _**"It looks like you are trying to deposit to an exchange that might not be able to process Multisig transactions or aggregates, please proceed with caution"**_

**Comment by jabo38** [comment] 2021-04-20 14:56
of course people sending from a regular account would not get this warning

**Comment by cryptoBeliever** [comment] 2021-06-05 10:42
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1451

**Closed by cryptoBeliever** 2021-06-05 10:42 UTC
Labels: P3 Issue
