### ISSUE TITLE
Harvesting - vrf and remote account private keys shared between profiles

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1117] opened 2021-02-13 12:06 UTC
Steps:

1. Create a profile with password X
2. Send more than 10000 XYM and start harvesting
3. Create a second profile with a password Y
4. Import private key of harvesting account from profile X

Result: On harvesting page we have "Show private key" for VRF and Remote but of course they can't be decrypted because password don't match.

Expected result: VRF/Remote account keys shouldn't be shared between profiles.

**Comment by cryptoBeliever** [comment] 2021-02-15 21:49
It's a very rare case. We aggreged change it to P3.

**Comment by Peersyst** [comment] 2021-04-01 09:45
Duplicate of #1370

**Closed by Peersyst** 2021-04-01 09:45 UTC
Labels: P3 Issue, harvesting, sprint-1
