### ISSUE TITLE
Mnemonic stays in memory when doing logout

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#1283] opened 2021-03-10 15:14 UTC
The mnemonic stays inside the memory if you make a new account then logout and make another account.

Steps to reproduce:
Make a new account using mnemonic.
Logout
Make a new account using mnemonic.
-> Previous mnemonic is displayed

**Comment by cryptoBeliever** [comment] 2021-03-10 16:16
As far as I remember it was already reported and fixed. Could you check live build http://desktop-build.symboldev.com/?

**Comment by cryptoBeliever** [comment] 2021-03-10 16:41
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1253

**Closed by cryptoBeliever** 2021-03-10 16:41 UTC
