### ISSUE TITLE
Foreign transactions are visible on wallet, after creating several accounts in one wallet and filling them from a faucet

### ISSUE THREAD

**Issue by DrCryptos** [nemgrouplimited/symbol-desktop-wallet#477] opened 2020-07-23 11:05 UTC
Wallet version 0.12 (0.9.6.3)

1. Launch a wallet that already has an account (for example, Account0). We are not logging into account
2. Create another account - Account21. We go through the whole procedure. We save the wallet address. Log out of your account
3. Create another account - Account22. We go through the whole procedure. We save the wallet address. Log out of your account
4. Create another account - Account23. We go through the whole procedure.
5. In the "Account" section, click on the faucet link.
6. The wallet is open.
7. The faucet page opens with the address Account23
8. Enter 1000, "CLAIM!"
9. We see new transactions in the wallet. We don't close the wallet, we don't change the account !!!
10. On the faucet page, insert the address Account21
11. Enter 2500, "CLAIM!"
12. IN THE WALLET, with an open account Account23, NEW TRANSACTIONS from the operation with Account21 are visible !!!
13. On the faucet page, insert the address Account22
14. Enter 5000, "CLAIM!"
15. IN THE WALLET, with an open account Account23, NEW TRANSACTIONS from the operation with Account22 are visible !!!

If after that you leave Account23 and go to Account0, and try to repeat the above steps, everything will be correct - "Foreign" transactions will not be visible

**Comment by cryptoBeliever** [comment] 2020-07-25 08:47
I think it's duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/460

**Comment by evias** [comment] 2020-07-29 10:06
Duplicate of #460 which got merged in latest main. To be added to next release :+1:

Thank you for the report @cryptoBeliever and @DrCryptos :+1: :+1:

**Closed by evias** 2020-07-29 10:06 UTC
Labels: bug, story-3
