### ISSUE TITLE
[Bug] Transaction link popup window is not fully visible

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#756] opened 2020-12-01 09:55 UTC
v0.13.5

Two places where this bug can be found:

1) WTR:
1. Go to Home page -> Transfer 
2. Put any account address into `To` field
3. Hover over the link sign at the bottom of the page
4. Hover over the copy sign 
Result: you can see that popup windows are not fully visible

![image](https://user-images.githubusercontent.com/11311924/100723362-dfccbc80-33eb-11eb-810b-771b341ca04e.png)

![image](https://user-images.githubusercontent.com/11311924/100724425-10f9bc80-33ed-11eb-8fd3-3c0439a80f42.png)

2) WTR
1. Go to Aggregate page ->Simple transaction
2. Put any account address into `To` field
3. Hover over the link sign at the bottom of the page

Result: you can see that transaction popup window is not fully visible

![image](https://user-images.githubusercontent.com/11311924/100724836-84033300-33ed-11eb-8916-a956dec232cb.png)

**Comment by cryptoBeliever** [comment] 2020-12-01 10:37
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/671

**Closed by cryptoBeliever** 2020-12-01 10:37 UTC
