### ISSUE TITLE
Address book import - issue when adding for second time 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#736] opened 2020-11-25 06:29 UTC
When you click the import address book , upload the address book (json file) on first go , it is working, but the scenario i tried is I uploaded a invalid address file , it gave invalid address, but when i uploaded the correct one, it is still showing invalid address,not moving further 
![image](https://user-images.githubusercontent.com/49143210/100191100-94ab3900-2f15-11eb-9d4b-8f9d319d3830.png)
![image](https://user-images.githubusercontent.com/49143210/100191158-adb3ea00-2f15-11eb-8ad7-66ec6e74867b.png)

**Comment by cryptoBeliever** [comment] 2020-12-01 11:54
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/724

**Closed by cryptoBeliever** 2020-12-01 11:54 UTC
