### ISSUE TITLE
Send button in Multisig not working

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#708] opened 2020-11-19 12:04 UTC
Pressing the send button on the multisig screen does not work.
If however the number of Removal or Approval is larger than the amount of cosigners provided or if they are set to 0 an error occurs . Yes, this is normal behaviour, but if everything is filled in correctly nothing happens when pressing the send button.
Vesion 0.13.5
This only happens with 1 account, that has previously been a multisig account. Also mint approval and min removal is set to 0 when starting the multisig process, with other accounts they start with 1.
Failing account:
![image](https://user-images.githubusercontent.com/6676974/99664123-fbd57300-2a67-11eb-8e6c-8a0684ca5bf2.png)
Working account:
![image](https://user-images.githubusercontent.com/6676974/99664210-1f98b900-2a68-11eb-8b34-090e1a2868e6.png)
 Failing account private key: 7B2C08AE43326B3D53DE46A437E4639A44D1885C3D84A52061983430ADEA36B2

**Comment by cryptoBeliever** [comment] 2020-11-19 21:38
@meyns what node are you using and what system?
I created new profile and imported this private key. When I go to multisig tab I see:

![image](https://user-images.githubusercontent.com/17684281/99727214-ec7e1600-2ab7-11eb-85f3-2e443993d024.png)

**Comment by cryptoBeliever** [comment] 2020-12-02 19:37
@meyns ping :) Could you also verify on live build (http://desktop-build.symboldev.com/)?

**Comment by cryptoBeliever** [comment] 2021-01-11 19:02
@meyns I was unable to reproduce. I'm closing. Please let me know if you can still reproduce it.

**Closed by cryptoBeliever** 2021-01-11 19:02 UTC
Labels: story-3
