### ISSUE TITLE
Private Network Support on Desktop Wallet

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#1142] opened 2021-02-16 16:13 UTC
Currently, the desktop wallet doesn't support private networks but it should.

On the profile creation page, we should be able to select `Private` or `Private Test` and specify the private network node's URL in the form.

**Comment by cryptoBeliever** [comment] 2021-02-20 19:23
@yilmazbahadir is this bug or more enhancement?

**Comment by yilmazbahadir** [comment] 2021-06-05 14:07
Yes, I think it's a duplicate. I think it's an enhancement.

**Comment by cryptoBeliever** [comment] 2021-06-05 14:09
Closed as duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/752

**Closed by cryptoBeliever** 2021-06-05 14:09 UTC
Labels: P3 Issue
