### ISSUE TITLE
Symbol blockchain Explorer - 404 error found.

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#554] opened 2020-10-09 10:39 UTC
defect description: when you click the symbol explorer link , getting 404 error(404 not found)
Steps: to reproduce:
1. login to symbol wallet with user credentials
2. click the tab accounts tab
3. click the symbol explorer link
4,. getting 404 not found message 

![image](https://user-images.githubusercontent.com/49143210/95573687-7793d700-0a49-11eb-8ac1-bb6a79e207fb.png)

**Comment by yilmazbahadir** [comment] 2020-10-09 11:08
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/543 and already fixed with https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/552

**Closed by yilmazbahadir** 2020-10-09 11:08 UTC
