### ISSUE TITLE
Mosaic supply cannot be Decreased, only Increased

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#562] opened 2020-10-13 15:27 UTC
Created my own mosaic (transferable, supply mutable but not restrictable) and tried to edit it to decrease its supply.
No matter what I select in the "Supply Change Direction:" box, the "Direction" field in the "Sign a transaction" dialog always says "Increase".
If I execute the transaction, it is indeed increased, not decreased as I selected.

Happens both with Desktop Wallet 12.1 and 13.1 (Windows).

**Comment by JackNEM** [comment] 2020-10-13 16:11
duplicate of #497

**Comment by yilmazbahadir** [comment] 2020-10-14 18:36
duplicate of #498

**Closed by yilmazbahadir** 2020-10-14 18:36 UTC
