### ISSUE TITLE
validation failed when adding co-signer

### ISSUE THREAD

**Issue by kiwiminer** [nemgrouplimited/symbol-desktop-wallet#1380] opened 2021-03-29 22:40 UTC
If i add a cosigner account to an address, its giving me the error "validation failed because redundant cosigners are present"
The message appears after clicking confirm on the aggregate bonded transaction at the top of the list.
im using ledger.
![photo_2021-03-30_11-30-51](https://user-images.githubusercontent.com/8110842/112908594-479dd480-914c-11eb-8873-6547a6a4eb6d.jpg)

**Comment by Peersyst** [comment] 2021-03-30 10:14
Thanks for the feedback! Could you provide some specific steps that reproduce the error?

**Comment by kiwiminer** [comment] 2021-03-31 09:47
> 
> 
> Thanks for the feedback! Could you provide some specific steps that reproduce the error?

basically im trying to add a multisig cosigner to a 1 of 1 account, as i need to add a new address so i can remove the old one.

The transaction will appear after adding the co-signer as an aggregate bonded transaction, in this case the one in the top of the screenshot. 
I click on the transaction, and then click confirm, then sign on the ledger and the error appears like in the screenshot.
I can send you a video in private if you like.

**Comment by bassemmagdy** [comment] 2021-05-18 16:10
Hi @kiwiminer are you still able to reproduce this on [latest-version](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v1.0.3)? if yes, would you mind sharing the video for the exact steps reproducing that?

**Comment by kiwiminer** [comment] 2021-05-18 22:45
> 
> 
> Hi @kiwiminer are you still able to reproduce this on [latest-version](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v1.0.3)? if yes, would you mind sharing the video for the exact steps reproducing that?

Hi @bassemmagdy I think the issue was at allnodes end, apparently they were required to have signed it at their end rather than me, but they were not being co-operative, so I ended up starting another new node on there and it went away with no issues.

**Comment by cryptoBeliever** [comment] 2021-06-04 19:08
This looks like a duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1398.
I did not hear about other such cases after Ledger integration fix.

**Closed by cryptoBeliever** 2021-06-04 19:08 UTC
Labels: P2 Issue
