### ISSUE TITLE
Encrypt message - for the first transaction the encrypt message is not working 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#753] opened 2020-12-01 06:34 UTC
I created an account , added XEM amount, and i tried to transfer amount, during that transaction, i clicked the encrypt messgae , i'm getting error. is this the right behaviour i.e for the first transaction, it will show error message .please confirm
![image](https://user-images.githubusercontent.com/49143210/100705470-3e367280-33cd-11eb-9181-69d90f7cc70a.png)

**Comment by cryptoBeliever** [comment] 2020-12-01 08:49
@surekabpm this is expected behaviour.
@yilmazbahadir maybe we can add a more descriptive message?

**Comment by bassemmagdy** [comment] 2020-12-14 10:54
@surekabpm is this still reproducible? could you please verify and make a video if possible?

**Comment by surekabpm** [comment] 2020-12-14 11:46
this issue is resolved now , i was able to transfer XEM amount , included encrypt message and it worked and that was the first transaction
![image](https://user-images.githubusercontent.com/49143210/102077787-da319680-3e2f-11eb-8a15-b961a9ee7288.png)
![image](https://user-images.githubusercontent.com/49143210/102077907-08af7180-3e30-11eb-8a73-07e78ec1e02a.png)

**Comment by surekabpm** [comment] 2020-12-14 11:46
i believe we can close this issue , hence closing

**Comment by cryptoBeliever** [comment] 2020-12-14 18:07
@bassemmagdy 
Well I commented here https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/753#issuecomment-736319371
Still message could be more descriptive ...

**Comment by Eugenity** [comment] 2021-01-26 12:53
The issue is reproducible again/still. The reason is now that the recipient does not have the outgoing transaction. Once the recipient has successfully announce the outgoing transaction the ecrypt function works for the sender.

**Comment by Eugenity** [comment] 2021-01-26 12:57
[Video](https://share.getcloudapp.com/v1uN1ArA)

**Comment by Eugenity** [comment] 2021-02-05 12:55
Not reproducible anymore. Closing.

**Closed by Eugenity** 2021-02-05 12:55 UTC
Labels: P3 Issue, aesthetic bug, story-2
