### ISSUE TITLE
Harvesting - problem starting harvesting for multisig

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1434] opened 2021-04-15 17:25 UTC
(I'm not able reproduce each time)

1. Start harvesting (link keys) for multisig account.
![image](https://user-images.githubusercontent.com/17684281/114912314-2281b500-9e20-11eb-974e-2cbfbe26e7ac.png)
2. "Request Harvesting"
![image](https://user-images.githubusercontent.com/17684281/114912370-34fbee80-9e20-11eb-9735-3d428bfe8b8e.png)
Transaction details are not presented (not able to start harvesting):
![image](https://user-images.githubusercontent.com/17684281/114912422-43e2a100-9e20-11eb-8c26-78133b381333.png)

**Comment by AdriaCarrera** [comment] 2021-05-04 10:11
Duplicate of #1435

**Closed** 2021-05-04 10:11 UTC
