### ISSUE TITLE
Cannot activate harvesting via symbol desktop wallet

### ISSUE THREAD

**Issue by fajarvm** [nemgrouplimited/symbol-desktop-wallet#1379] opened 2021-03-29 18:01 UTC
Prerequisites:
After the keys are linked to a node, the harvesting status says `KEYS LINKED`.
To activate harvesting via symbol desktop wallet v1.0.0, users are prompted to enter the password twice to confirm activation. 

The problem:
After entering the password for the second time, the "sign transaction" pop-up dialog stays and nothing happens.
The harvesting status stays at `KEYS LINKED`.

Screenshot:
<img width="1023" alt="Screenshot 2021-03-29 at 19 57 56" src="https://user-images.githubusercontent.com/3041538/112879517-86d71180-90c9-11eb-83ef-7b5f8a731290.png">

Error shown in the console:
<img width="876" alt="Screenshot 2021-03-29 at 19 53 11" src="https://user-images.githubusercontent.com/3041538/112879535-8b9bc580-90c9-11eb-8b15-a23eb8f73a5f.png">

**Comment by fajarvm** [comment] 2021-03-29 18:25
UPDATE: After restarting the desktop wallet, it's now possible to sign the transaction and activate harvesting.

**Comment by cryptoBeliever** [comment] 2021-06-04 18:25
@fajarvm I was unable to reproduce on 1.0.3 so I'm closing. Please ping me if you still can reproduce.

**Closed by cryptoBeliever** 2021-06-04 18:25 UTC
Labels: P3 Issue, harvesting, needs reproduction
