### ISSUE TITLE
"Unknown publisher" warning during windows/mac (exe/dmg) installation

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#720] opened 2020-11-20 19:40 UTC
We should be signing the code during the "npm run release" step.

Please see https://www.electron.build/code-signing

**Comment by cryptoBeliever** [comment] 2021-01-26 20:37
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/903

**Closed by cryptoBeliever** 2021-01-26 20:37 UTC
Labels: P3 Issue, aesthetic bug
