### ISSUE TITLE
A user is able to create an empty contact [Bug]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#791] opened 2020-12-09 11:40 UTC
**Steps to reproduce:**

1. Go to Accounts / My contacts
2. Click on "Add contact" button
3. Click "Confirm" button w/o providing any information in the fields

**Expected result:** Pop-ups informing a user that the fields are required are displayed
**Actual result:** An empty contact is saved to the contacts list

[Video](https://share.getcloudapp.com/6quxxRPO)

Those empty entries are reflected on the Transfer page while selecting a contact

**Comment by cryptoBeliever** [comment] 2020-12-09 13:11
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/737

**Closed by cryptoBeliever** 2020-12-09 13:11 UTC
Labels: P3 Issue, bug
