### ISSUE TITLE
Date display error

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#666] opened 2020-11-11 22:20 UTC
The date on the dashboard seems to be wrong. It shows 2 hours in the future for users from Japan.

**Comment by cryptoBeliever** [comment] 2020-11-11 23:06
He @trestoJP. It's duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/545.
I will ping devs regarding this issue.
Thank you.

**Comment by cryptoBeliever** [comment] 2020-11-19 07:02
Fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5

**Closed by cryptoBeliever** 2020-11-19 07:02 UTC
