### ISSUE TITLE
Can not created additional child accounts and the Seed account appears twice. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1249] opened 2021-03-04 20:22 UTC
I make a passphrase, go to my wallet, try to create an additional account multiple times in a row. I end up creating an extra seed address. Also after the 2nd address was created on the 3rd try, I can't create anymore. 

Here is a screen shot. 

I'm using a Mac build of Version: 0.13.8 and I've actually had this problem before in the past too. 

![image](https://user-images.githubusercontent.com/10395907/110025331-9602b380-7d05-11eb-8ff7-73e88205367d.png)

![image](https://user-images.githubusercontent.com/10395907/110025357-9e5aee80-7d05-11eb-9c3b-3147b0bc9387.png)

Not sure if it is related to the passphrase or not or any other issues with account creation

Seed: pyramid opinion silly month order envelope artwork saddle black since fiber guitar
notable belt certain device toe retire quick vacuum behave hire palace trap

**Comment by cryptoBeliever** [comment] 2021-03-04 21:04
May be related with: https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1246

**Comment by jabo38** [comment] 2021-03-04 21:06
looks like the same error more or less as #1246

**Comment by bassemmagdy** [comment] 2021-03-05 00:43
@jabo38 nope these issues are different, but I'm thinking how could you reproduce it, as that was a result of the submit button not having a loader for the async operation which is not the case now.

**Comment by NikolaiB** [comment] 2021-03-31 07:42
@jabo38 @bassemmagdy @cryptoBeliever I can not reproduce it.

**Comment by Eugenity** [comment] 2021-03-31 11:55
I also could not reproduce this issue. FYI: There was pretty the same issue which was fixed in February: [949](https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/949)

**Comment by cryptoBeliever** [comment] 2021-06-05 10:45
Because nobody is able to reproduce, I'm closing the issue.

**Closed by cryptoBeliever** 2021-06-05 10:45 UTC
Labels: needs reproduction
