### ISSUE TITLE
Created an account from scratch. Found XYM in it. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#598] opened 2020-10-27 18:03 UTC
I created an account from scratch today on 10-27 using the website http://desktop-build.symboldev.com/#/profiles/create. 

I created a random passphrase, not importing an old one. 

I created child accounts. This should be all random too. They were. 

I took a private key from one random child account and went back to http://desktop-build.symboldev.com/#/profiles/create to create a private key wallet from the new profile screen. 

![image](https://user-images.githubusercontent.com/10395907/97342607-67a33200-1854-11eb-83d6-b80da6f483b7.png)

I entered the private key from my fresh account. 2EED255FD0CD80370D0471B072C9397681268B98A429D938247AD5DCD9C1196F

The account was as expected and I could see my tx history. 

I started to create child accounts deterministically from that account. Only to find accounts already funded days before on 10-23. How can accounts be created deterministically from a passphrase I just made today on a link for a web wallet I just got today have txs from 3 days ago? Somebody else clearly was already able to deterministically create them. And now we have two people starring the same schema!

**Comment by rg911** [comment] 2020-10-27 19:52
Hi @jabo38 , we are still working on the profiles at the moment. Already noticed the issue. 
The new profile structure will be:

 Root Mnemonic account
      Child account
      Child account
      Child account
      .... (up to 10)
PrivateKey account 
PrivateKey account 
PrivateKey account 
PrivateKey account 


Mnemonic account(s) and private key account(s) will co-exists in one single profile

**Comment by cryptoBeliever** [comment] 2020-11-19 09:51
@jabo38 could you verify on current version?

**Comment by jabo38** [comment] 2020-11-24 16:21
I was on whatever version was being uploaded on http://desktop-build.symboldev.com/ at that time. I don't know what the version was.

**Comment by yilmazbahadir** [comment] 2020-11-25 10:01
Hi @jabo38, the latest release should fix this issue, can you test and close the issue if resolved?

**Comment by bassemmagdy** [comment] 2020-11-30 11:12
Thanks, @jabo38 for reporting the issue,  Since the latest wallet release doesn’t allow users to create child accounts from a private key seeded wallet only passphrase seeded wallets, also creating a profile from importing a private key isn't an available option right now, Meaning that the issue should be non-reproducible anymore.

**Closed by bassemmagdy** 2020-11-30 11:12 UTC
