### ISSUE TITLE
Not showing latest transactions

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#578] opened 2020-10-19 06:58 UTC
The wallet is not showing the latest transactions, but transactions from 3 days ago. The explorer is showing the correct latest transactions. Desktop wallet v0.13.1
Explorer:
http://explorer-0.10.0.x-01.symboldev.network/accounts/TCCZ6DAUR37RWCCARM3SC3263SSSOMZRYGJNAJY
![image](https://user-images.githubusercontent.com/6676974/96411592-fbd42000-11e8-11eb-8c55-aa246faddfc1.png)
Desktop wallet:
![image](https://user-images.githubusercontent.com/6676974/96411627-0bebff80-11e9-11eb-8d28-a075b0752b19.png)
Wallet private key: 17B9E0BFA9F888835ED91899EF79BF52BA248191F658606FA19AD7DDA61B3A71

**Comment by yilmazbahadir** [comment] 2020-10-19 07:19
I couldn't reproduce the issue after importing the private key. This is the screenshot of the wallet tx list  :

![Screenshot 2020-10-19 at 08 13 57](https://user-images.githubusercontent.com/6256269/96413354-6eda9800-11e3-11eb-826e-27716c1c1b21.png)

**Comment by meyns** [comment] 2020-10-20 06:36
Looks different for me:
![image](https://user-images.githubusercontent.com/6676974/96549119-5637b400-12af-11eb-9855-8df81c4c847c.png)

**Comment by meyns** [comment] 2020-11-05 15:45
All looks good in latest version

**Comment by cryptoBeliever** [comment] 2020-11-19 07:10
OK, closing

**Closed by cryptoBeliever** 2020-11-19 07:10 UTC
