### ISSUE TITLE
Confusing messages next to fee selector

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1496] opened 2021-05-17 05:45 UTC
Currently, when the user is doing a transaction, then he can see a message like:
"Please note that the minimum fee multiplier for the currently selected node is XX" next to fee selector.

What user supposed to do with this message? Is this good or wrong that the multiplier is XX?
What information does it give to the user? Maybe we should warn only for high multiplier (high fees)?

**Comment by segfaultxavi** [comment] 2021-05-17 06:37
I totally agree with this concern.
Right now the dropdown already shows the final fee to pay, so maybe this message can be removed completely.

**Comment by OlegMakarenko** [comment] 2021-05-17 11:03
Duplicate of #1443

**Comment by cryptoBeliever** [comment] 2021-05-17 11:19
Missed that, Thanks @OlegMakarenko :+1:

**Closed** 2021-05-17 11:20 UTC
