### ISSUE TITLE
A partial transaction that should sign doesn't appear in the account transaction list.

### ISSUE THREAD

**Issue by daoka** [nemgrouplimited/symbol-desktop-wallet#943] opened 2021-01-20 16:05 UTC
Application ver: 0.13.8 (mac)

When I convert an account to a multi signature.
Cosinatory's partial transaction list should be shown the multisig modification transaction, but It is not shown.
So cosignatory can not cosign.

here is the video capture.
https://drive.google.com/file/d/1LWhbI8DqxNk3Hz8N-7_QgU0v5chh_ckW/view?usp=sharing

**Comment by rg911** [comment] 2021-01-20 16:28
Hi @daoka which node you are using in the wallet?

**Comment by daoka** [comment] 2021-01-20 16:59
I'm using api-01-us-west-1 in the wallet
http://api-01.us-west-1.testnet.symboldev.network:3000/

**Comment by rg911** [comment] 2021-01-20 17:57
Hmm, I am using the same node, but cannot reproduce the error. We had a known issue on modifying multisig, but convert moultisig works as expected

**Comment by cryptoBeliever** [comment] 2021-01-26 20:03
@daoka are you able to reproduce on other node than http://api-01.us-west-1.testnet.symboldev.network:3000/?

**Comment by daoka** [comment] 2021-01-28 08:52
@cryptoBeliever 
I've tried another node `api-01-eu-central-1
http://api-01.eu-central-1.testnet.symboldev.network:3000`
It didn't reproduce. It was success.

**Comment by cryptoBeliever** [comment] 2021-02-02 21:38
@rg911 
This was most probably related to closed WebSockets (Funds Lock confirmed but Aggregate not announed).
I'm closing because we have another issue for that: https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1011

**Closed by cryptoBeliever** 2021-02-02 21:38 UTC
Labels: P2 Issue, bug
