### ISSUE TITLE
Adding Russian translation (symbol-desktop-wallet)

### ISSUE THREAD

**Issue by klimgeran** [nemgrouplimited/symbol-desktop-wallet#491] opened 2020-08-11 05:26 UTC
I will add Russian translation for symbol-desktop-wallet

**Comment by klimgeran** [comment] 2020-08-20 00:38
@dgarcia360

**Comment by cryptoBeliever** [comment] 2021-06-04 20:07
@klimgeran if you consider adding Russian translation you can create a pull request.
Language files are here https://github.com/nemgrouplimited/symbol-desktop-wallet/tree/main/src/language

**Comment by cryptoBeliever** [comment] 2021-06-05 10:32
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1478

**Closed by cryptoBeliever** 2021-06-05 10:32 UTC
Labels: enhancement
