### ISSUE TITLE
Symbol Wallet for Windows not auto refreshing chain.

### ISSUE THREAD

**Issue by rickd-dotshite** [nemgrouplimited/symbol-desktop-wallet#1348] opened 2021-03-19 18:18 UTC
The chain height, balance etc changes only if you change node or restart.

**Comment by myxmaster** [comment] 2021-03-21 12:26
Possible duplicate of #1264.

**Comment by rickd-dotshite** [comment] 2021-03-21 21:12
Not sure, that is sometimes, this is always. Probably part of the same bug, but needs the clarification that the chain height, balance etc doesn't auto refresh ever without at least a node change. Transaction refresh doesn't do it either.

**Comment by Peersyst** [comment] 2021-03-22 14:49
Duplicate of #1264

**Closed by Peersyst** 2021-03-22 14:49 UTC
