### ISSUE TITLE
Mosaic definition is displayed as Aggregate transaction

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1087] opened 2021-02-09 12:39 UTC
**Steps to reproduce:**

1. Go to Mosaics page
2. Click on 'Create new mosaics' tab
3. Specify aт arbitrary mosaic
4. Confirm a mosaic definition
5. Go to Dashboard

**Expected result:** The mosaic definition is indicated as 'Mosaic definition' on the dashboard
**Actual result:** The mosaic definition is indicated as Aggregate transaction

NOTE: The mosaic definition is dispalyed right when done from Aggregate page

[Screnshot](https://share.getcloudapp.com/12uoN7rY)

**Comment by OlegMakarenko** [comment] 2021-02-09 18:26
Actually to create a new mosaic with a defined supply the wallet announce aggregate complete transaction that consist of `Mosaic Definition` and `Mosaic Supply Change` inner transactions. That's why it is displayed as an aggregate transaction on the dashboard. 

When you announce just a `Mosaic Definition` it will creates a mosaic with 0 supply.

**Comment by cryptoBeliever** [comment] 2021-02-13 10:55
Yes. This is not a bug. Presentation will be improved when https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090 will be fixed.

**Closed by cryptoBeliever** 2021-02-13 10:55 UTC
Labels: P3 Issue
