### ISSUE TITLE
multisig tx cosigners took maybe two hours to sign and the tx was already timed out

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1327] opened 2021-03-17 04:07 UTC
I made a hash lock tx for a mutlsig tx here. http://explorer.symbolblockchain.io/transactions/F8F26F6A8860E208B4E499E2CE4B7DBA52F3DCFD32CB32DAE6B956EC8F6020DD

less than 250 blocks later I wanted to sign and the tx was no longer there to sign. I'm not sure how long it takes before a multisig tx to expire, but the current default right now is not giving people a lot of time to sign.

**Comment by Peersyst** [comment] 2021-03-24 10:51
Duplicate of #1203

**Closed by Peersyst** 2021-03-24 10:51 UTC
