### ISSUE TITLE
Unable to create a multi-level multisig account

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#1394] opened 2021-04-05 09:59 UTC
Unable to create the following multi-leve multisig account:

multisig account A(1 of 1)
 +multisig account B(1 of 1)
   +normal account C

- STEPS TO REPRODUCE
 wallet-version: symbol-desktop-wallet_1.0.1.all

1. Create multisig account B(1 of 1) by adding the normal account C as co-signer
 -> it's good!
2. Create multisig account A(1 of 1) by adding account B as a co-signer
 -> it is not good. 

account B and account C get the following dialog in desktop wallet,
so both accounts are no longer able to do anything.
![image](https://user-images.githubusercontent.com/28587337/113562249-bf826800-9640-11eb-9bfd-5e41dc5689da.png)

could you check it, please?

**Comment by Peersyst** [comment] 2021-04-08 14:40
Hi, we are currently working on it and will be fixed in the next sprint.
Closing this as it is Duplicate of #1350

**Closed by Peersyst** 2021-04-08 14:40 UTC
