### ISSUE TITLE
Duration of Namespace rental adds 1 day.

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1520] opened 2021-06-08 08:48 UTC
WTR:

1. Create Namespace with standard 30 days duration period
2. Go to Owned Namespaces page

Result: 
1. You can see that the duration period is `31 d 23 h 43 m` that is incorrect.
2. The time is not reducing from UI
![image](https://user-images.githubusercontent.com/11311924/121153922-4c77b680-c868-11eb-9cb3-5c08f398e01e.png)

**Comment by AnthonyLaw** [comment] 2021-06-08 15:01
I tested my local, I can't reproduce this issue.

![Screenshot 2021-06-08 at 10 57 34 PM](https://user-images.githubusercontent.com/5649156/121209350-5c65b980-c8ad-11eb-8015-787a2d57c075.png)
![Screenshot 2021-06-08 at 10 58 14 PM](https://user-images.githubusercontent.com/5649156/121209357-5e2f7d00-c8ad-11eb-97f2-d08e490f6f6e.png)
![Screenshot 2021-06-08 at 10 59 18 PM](https://user-images.githubusercontent.com/5649156/121209364-5f60aa00-c8ad-11eb-8df3-626ada753e48.png)

**Comment by NikolaiB** [comment] 2021-06-08 15:48
@AnthonyLaw if we set 30 days, in any case it won't be more than 29 days 23hours, but on your screenshot is 30 days 23 hours.

**Comment by coiki** [comment] 2021-06-10 12:15
User Story: “As a user that registered a namespace, I want the duration of the rental to be accurate when displayed, down to the minute, so I know when my namespace rental will expire and act accordingly.”

Acceptance Criteria:
- AC1: When displaying list of registered Namespaces, the duration displayed should be consistent with the duration I chose when registering that Namespace.

**Comment by coiki** [comment] 2021-06-10 12:16
@AnthonyLaw seems from your screenshots that the label displays +1 day. The error could be on either part (saving config, or displaying). Did you confirm this from your side? Thanks.

**Comment by NikolaiB** [comment] 2021-06-22 06:57
fixed

**Comment by cryptoBeliever** [comment] 2021-06-25 20:57
Fixed in integration branch.

![image](https://user-images.githubusercontent.com/17684281/123484472-afa76e00-d608-11eb-96e2-7358e75c3f48.png)

**Closed by cryptoBeliever** 2021-06-25 20:57 UTC
Labels: P2 Issue
