### ISSUE TITLE
Incorrect display of the harvesting status of the same account on two different devices

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#953] opened 2021-01-21 21:02 UTC
I have the same wallet installed on two devices. Although harvesting has been successfully activated for one account, it is not displayed on the other device. Only KEYS LINKED.
This means that if you restore the account on another device, you may have an incorrect display of the delegated harvesting status.

**Comment by cryptoBeliever** [comment] 2021-01-24 08:47
I think it is related to that app don't know which one IP has a node connected to.
@rg911 can we improve it?

**Comment by cryptoBeliever** [comment] 2021-01-26 19:49
It works the same in NIS1. For now, I marking it as an improvement.

**Comment by NikolaiB** [comment] 2021-03-19 15:11
There is another related issue https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1243

Please note that users also report that if the node is changed on one device it doesn't show on another one: 
![image](https://user-images.githubusercontent.com/11311924/111801902-98fdc680-88f7-11eb-8f3b-fd9f1a0043fe.png)
![image](https://user-images.githubusercontent.com/11311924/111801972-af0b8700-88f7-11eb-95eb-8fb0d7d35e80.png)

**Comment by Peersyst** [comment] 2021-03-24 11:05
Duplicate of #1243

**Closed by Peersyst** 2021-03-24 11:05 UTC
Labels: P1 Issue
