### ISSUE TITLE
A user is unable to successfully initiate a Multisig transaction using co-signer account from different profile

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1005] opened 2021-02-01 18:35 UTC
**Steps to reproduce:**

1. Create a Multisig for an account using addresses from a separate profiles
2. Add 2 co-signers (tested with such number of co-signatories), each from a different profile (those 2 can be in one account, one seed) for a transaction approving and 1 for a removal
3. Initiate a transaction from one of the co-signers
**Expected result:**  Funds lock transaction is successful, new transaction appears for all co-signers, they can sign a transaction
**Actual result:** Only funds lock transaction appears for a initiating co-signer, not going further 

ps: w/o a screenshot or video since long to capture

A user is able to successfully initiate a transaction for a multisig when a co-signers are within the same profile

**Comment by cryptoBeliever** [comment] 2021-02-01 19:16
I'm not able to reproduce. I checked on http://desktop-build.symboldev.com/
If indeed Aggregate was not announced I suppose it's another reason (for example bad node) than sending from another profile.
Please give steps to reproduce.

**Comment by Eugenity** [comment] 2021-02-02 15:54
That's quite strange, cause simpe transactions are OK, I was able to send from different accounts many times. But with multisig I am not only unable to announce a transaction successfully but also cannot reduce number of the signers or the latest time I cannot even create a new Mutisig. Could I somehow messed up with the accouts so they won't work in the Multisig part?

**Comment by cryptoBeliever** [comment] 2021-02-02 16:48
What wallet are you using (version and platform)?
Could you check on live build version if you getting some errors in Chrome console?

**Comment by Eugenity** [comment] 2021-02-02 17:14
api-01-us-west-1
I did not see any specific errors in the console whilst waiting for a transaction being announced. 
[Video](https://www.loom.com/share/69b6add9748744948709ae3f1f879f04)

**Comment by Eugenity** [comment] 2021-02-02 17:14
I was using live build.

**Comment by cryptoBeliever** [comment] 2021-02-02 22:58
It's most probably related to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1011
Please verify when it will be solved.

**Comment by cryptoBeliever** [comment] 2021-02-06 19:25
@Eugenity could you check if you still able to reproduce closed websockets? If yes please tell which one node and if work after switching node.

**Comment by Eugenity** [comment] 2021-02-08 10:06
@cryptoBeliever I have been unable to reproduce them so far using all default nodes.

**Comment by cryptoBeliever** [comment] 2021-02-11 21:46
Ok. Closing.

**Closed by cryptoBeliever** 2021-02-11 21:46 UTC
Labels: question
